### ISSUE TITLE
Unable to add members page

### ISSUE THREAD

**Issue by s4m13337** [gnulinuxindia/site#4]
Adding new markdown file in the /content/members directory creates error.

![photo_2024-04-23_20-16-37](https://github.com/gnulinuxindia/site/assets/57192603/0b35c574-ef4a-4770-8063-64440105e630)

The error possibly occurs at these lines from the index.astro page:

![photo_2024-04-23_20-16-54](https://github.com/gnulinuxindia/site/assets/57192603/5254fbd6-0c56-4ad8-bb1a-3a0b193d7832)

**Comment by gtlsgamr** [comment]
Fixed in f45e150
